# Generated by Django 4.2.7 on 2026-01-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id_model",
                    models.CharField(
                        db_column="id_model",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(db_column="model_name", max_length=50)),
                ("model_code", models.CharField(db_column="model_code", max_length=50)),
                (
                    "model_version",
                    models.CharField(
                        blank=True, db_column="model_version", max_length=20, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("capabilities", models.JSONField(blank=True, null=True)),
                (
                    "release_date",
                    models.DateField(blank=True, db_column="release_date", null=True),
                ),
                (
                    "is_latest",
                    models.BooleanField(db_column="is_latest", default=False),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="AIPlatform",
            fields=[
                (
                    "id_platform",
                    models.CharField(
                        db_column="id_platform",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(db_column="platform_name", max_length=50),
                ),
                (
                    "platform_code",
                    models.CharField(
                        db_column="platform_code", max_length=30, unique=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, db_column="company_name", max_length=100, null=True
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, db_column="logo_url", max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "release_date",
                    models.DateField(blank=True, db_column="release_date", null=True),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
            ],
            options={
                "verbose_name": "AI Platform",
                "verbose_name_plural": "AI Platforms",
                "db_table": "ai_platforms",
                "ordering": ["sort_order", "platform_name"],
            },
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id_avatar",
                    models.CharField(
                        db_column="id_avatar",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, db_column="avatar_url", max_length=255, null=True
                    ),
                ),
                (
                    "avatar_name",
                    models.CharField(
                        blank=True, db_column="avatar_name", max_length=50, null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatars",
                "db_table": "avatar",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id_category",
                    models.CharField(
                        db_column="id_category",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(db_column="category_name", max_length=50),
                ),
                (
                    "category_code",
                    models.CharField(
                        db_column="category_code", max_length=30, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, db_column="icon_url", max_length=255, null=True
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, db_column="color_hex", max_length=7, null=True
                    ),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prompthub.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["sort_order", "category_name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id_permission",
                    models.AutoField(
                        db_column="id_permission", primary_key=True, serialize=False
                    ),
                ),
                (
                    "permission_name",
                    models.CharField(db_column="permission_name", max_length=50),
                ),
                (
                    "permission_code",
                    models.CharField(
                        db_column="permission_code", max_length=50, unique=True
                    ),
                ),
                ("module", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent_permission",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_permission_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prompthub.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id_prompt",
                    models.CharField(
                        db_column="id_prompt",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "short_description",
                    models.TextField(
                        blank=True, db_column="short_description", null=True
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, db_column="thumbnail_url", max_length=255, null=True
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(db_column="is_premium", default=False),
                ),
                (
                    "ticket_cost",
                    models.SmallIntegerField(db_column="ticket_cost", default=0),
                ),
                (
                    "is_featured",
                    models.BooleanField(db_column="is_featured", default=False),
                ),
                (
                    "is_verified",
                    models.BooleanField(db_column="is_verified", default=False),
                ),
                ("view_count", models.IntegerField(db_column="view_count", default=0)),
                ("like_count", models.IntegerField(db_column="like_count", default=0)),
                ("save_count", models.IntegerField(db_column="save_count", default=0)),
                (
                    "share_count",
                    models.IntegerField(db_column="share_count", default=0),
                ),
                (
                    "comment_count",
                    models.IntegerField(db_column="comment_count", default=0),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        db_column="average_rating",
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(db_column="rating_count", default=0),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Pending"),
                            (3, "Published"),
                            (4, "Archived"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_column="published_at", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "db_table": "prompts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptLevel",
            fields=[
                (
                    "id_level",
                    models.SmallIntegerField(
                        db_column="id_level", primary_key=True, serialize=False
                    ),
                ),
                ("level_name", models.CharField(db_column="level_name", max_length=30)),
                ("level_code", models.CharField(db_column="level_code", max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "requires_premium",
                    models.BooleanField(db_column="requires_premium", default=False),
                ),
                (
                    "ticket_cost",
                    models.SmallIntegerField(db_column="ticket_cost", default=0),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Prompt Level",
                "verbose_name_plural": "Prompt Levels",
                "db_table": "prompt_levels",
            },
        ),
        migrations.CreateModel(
            name="PromptSource",
            fields=[
                (
                    "id_source",
                    models.CharField(
                        db_column="id_source",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(db_column="source_name", max_length=100),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, db_column="source_url", max_length=255, null=True
                    ),
                ),
                (
                    "source_type",
                    models.SmallIntegerField(db_column="source_type", default=1),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_verified",
                    models.BooleanField(db_column="is_verified", default=False),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Prompt Source",
                "verbose_name_plural": "Prompt Sources",
                "db_table": "prompt_sources",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id_role",
                    models.AutoField(
                        db_column="id_role", primary_key=True, serialize=False
                    ),
                ),
                ("role_name", models.CharField(db_column="role_name", max_length=50)),
                (
                    "role_code",
                    models.CharField(db_column="role_code", max_length=30, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role_level",
                    models.SmallIntegerField(db_column="role_level", default=1),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id_plan",
                    models.CharField(
                        db_column="id_plan",
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_name", models.CharField(db_column="plan_name", max_length=50)),
                (
                    "plan_code",
                    models.CharField(db_column="plan_code", max_length=20, unique=True),
                ),
                (
                    "plan_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Free"),
                            (2, "Basic"),
                            (3, "Pro"),
                            (4, "Enterprise"),
                        ],
                        db_column="plan_type",
                    ),
                ),
                ("duration_days", models.IntegerField(db_column="duration_days")),
                (
                    "ticket_amount",
                    models.IntegerField(db_column="ticket_amount", default=0),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percent",
                    models.DecimalField(
                        db_column="discount_percent",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                    ),
                ),
                ("features", models.JSONField(blank=True, null=True)),
                (
                    "max_prompts_per_day",
                    models.IntegerField(
                        blank=True, db_column="max_prompts_per_day", null=True
                    ),
                ),
                (
                    "can_access_premium",
                    models.BooleanField(db_column="can_access_premium", default=False),
                ),
                (
                    "can_download",
                    models.BooleanField(db_column="can_download", default=False),
                ),
                (
                    "can_use_api",
                    models.BooleanField(db_column="can_use_api", default=False),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
                (
                    "is_popular",
                    models.BooleanField(db_column="is_popular", default=False),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["sort_order", "plan_type"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id_tag",
                    models.AutoField(
                        db_column="id_tag", primary_key=True, serialize=False
                    ),
                ),
                ("tag_name", models.CharField(db_column="tag_name", max_length=30)),
                ("tag_slug", models.SlugField(db_column="tag_slug", unique=True)),
                (
                    "usage_count",
                    models.IntegerField(db_column="usage_count", default=0),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="PromptContent",
            fields=[
                (
                    "prompt",
                    models.OneToOneField(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="content",
                        serialize=False,
                        to="prompthub.prompt",
                    ),
                ),
                ("prompt_text", models.TextField(db_column="prompt_text")),
                (
                    "prompt_text_en",
                    models.TextField(blank=True, db_column="prompt_text_en", null=True),
                ),
                (
                    "usage_guide",
                    models.TextField(blank=True, db_column="usage_guide", null=True),
                ),
                (
                    "example_input",
                    models.TextField(blank=True, db_column="example_input", null=True),
                ),
                (
                    "example_output",
                    models.TextField(blank=True, db_column="example_output", null=True),
                ),
                ("tips", models.TextField(blank=True, null=True)),
                ("variables", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prompt Content",
                "verbose_name_plural": "Prompt Contents",
                "db_table": "prompt_content",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "config_key",
                    models.CharField(
                        db_column="config_key",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "config_value",
                    models.TextField(blank=True, db_column="config_value", null=True),
                ),
                (
                    "config_type",
                    models.CharField(
                        db_column="config_type", default="string", max_length=20
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_public",
                    models.BooleanField(db_column="is_public", default=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Config",
                "verbose_name_plural": "System Configs",
                "db_table": "system_config",
            },
        ),
        migrations.CreateModel(
            name="PromptTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.prompt",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="id_tag",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.tag",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_tags",
                "unique_together": {("prompt", "tag")},
            },
        ),
        migrations.CreateModel(
            name="PromptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(db_column="is_primary", default=False),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="id_category",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.category",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.prompt",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_categories",
                "unique_together": {("prompt", "category")},
            },
        ),
        migrations.CreateModel(
            name="PromptAuthor",
            fields=[
                (
                    "id_author",
                    models.CharField(
                        db_column="id_author",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(db_column="author_name", max_length=100),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "social_links",
                    models.JSONField(blank=True, db_column="social_links", null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "is_verified",
                    models.BooleanField(db_column="is_verified", default=False),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Author",
                "verbose_name_plural": "Prompt Authors",
                "db_table": "prompt_authors",
            },
        ),
        migrations.CreateModel(
            name="PromptAIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(db_column="is_recommended", default=False),
                ),
                (
                    "compatibility_score",
                    models.SmallIntegerField(
                        blank=True, db_column="compatibility_score", null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        db_column="id_model",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.aimodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.prompt",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_ai_models",
                "unique_together": {("prompt", "ai_model")},
            },
        ),
        migrations.AddField(
            model_name="prompt",
            name="ai_models",
            field=models.ManyToManyField(
                related_name="prompts",
                through="prompthub.PromptAIModel",
                to="prompthub.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_column="id_author",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompthub.promptauthor",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="categories",
            field=models.ManyToManyField(
                related_name="prompts",
                through="prompthub.PromptCategory",
                to="prompthub.category",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_prompts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="level",
            field=models.ForeignKey(
                db_column="id_level",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompthub.promptlevel",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                db_column="id_primary_category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_prompts",
                to="prompthub.category",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_column="id_source",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prompthub.promptsource",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="tags",
            field=models.ManyToManyField(
                related_name="prompts",
                through="prompthub.PromptTag",
                to="prompthub.tag",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_prompts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id_comment",
                    models.AutoField(
                        db_column="id_comment", primary_key=True, serialize=False
                    ),
                ),
                ("comment_text", models.TextField(db_column="comment_text")),
                ("like_count", models.IntegerField(db_column="like_count", default=0)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Visible"), (2, "Hidden"), (3, "Deleted")],
                        default=1,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_comment_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="prompthub.comment",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="prompthub.prompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="platform",
            field=models.ForeignKey(
                db_column="id_platform",
                on_delete=django.db.models.deletion.CASCADE,
                to="prompthub.aiplatform",
            ),
        ),
        migrations.CreateModel(
            name="UserPromptInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.BooleanField(db_column="is_liked", default=False)),
                ("is_saved", models.BooleanField(db_column="is_saved", default=False)),
                ("rating", models.SmallIntegerField(blank=True, null=True)),
                ("view_count", models.IntegerField(db_column="view_count", default=0)),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, db_column="last_viewed_at", null=True
                    ),
                ),
                (
                    "liked_at",
                    models.DateTimeField(blank=True, db_column="liked_at", null=True),
                ),
                (
                    "saved_at",
                    models.DateTimeField(blank=True, db_column="saved_at", null=True),
                ),
                (
                    "rated_at",
                    models.DateTimeField(blank=True, db_column="rated_at", null=True),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        db_column="id_prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.prompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Prompt Interaction",
                "verbose_name_plural": "User Prompt Interactions",
                "db_table": "user_prompt_interactions",
                "unique_together": {("user", "prompt")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_create",
                    models.BooleanField(db_column="can_create", default=False),
                ),
                ("can_read", models.BooleanField(db_column="can_read", default=True)),
                (
                    "can_update",
                    models.BooleanField(db_column="can_update", default=False),
                ),
                (
                    "can_delete",
                    models.BooleanField(db_column="can_delete", default=False),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="id_permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="id_role",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompthub.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(fields=["slug"], name="prompts_slug_64daf4_idx"),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(fields=["status"], name="prompts_status_afc0d5_idx"),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                fields=["created_by"], name="prompts_created_1c4c3b_idx"
            ),
        ),
    ]
