# Generated by Django 4.2.7 on 2026-01-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon class')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags (phân cách bằng dấu phẩy)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc (để hiển thị giảm giá)')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('suspended', 'Đã tạm dừng')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('thumbnail', models.ImageField(upload_to='prompts/thumbnails/%Y/%m/', verbose_name='Ảnh thumbnail')),
                ('preview_images', models.JSONField(blank=True, default=list, verbose_name='Ảnh preview (list URLs)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Lượt tải')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá trung bình')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Số đánh giá')),
                ('featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Đang thịnh hành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='core.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá đã thanh toán')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mua')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.prompt', verbose_name='Prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Số sao (1-5)')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.prompt', verbose_name='Prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('prompt', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='core_prompt_created_a2204f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['status', '-created_at'], name='core_prompt_status_bcd61a_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['featured', '-created_at'], name='core_prompt_feature_dc4a74_idx'),
        ),
    ]
